### PR TITLE
Colored Verification Levels

### PR DESCRIPTION
**Pull request by Bluscream**

### CODE REVIEW

**Comment by Bluscream** [comment]
Reason for close?

**Comment by cosmicsalad** [comment]
@Bluscream I'm not doing a single thing you request unless you take down your garbage BD+ plugins. You've created Discord cancer.

**Comment by Bluscream** [comment]
Hehe you're refusing to improve your theme GG have fun making everything on your own then, when i fix/improve something in your themes i will still make a pr cause people can use my pr'ed version then ;)

**Comment by cosmicsalad** [comment]
Lol what? I've already made everything on my own and I'm just refusing to implement anything you request because I don't respect you. Congrats on becoming an asshole and refusing to clean up your very poorly written BD plugins. 👌

**Pull request closed without merging**
